[workspace]
authors = ["Hameer Abbasi <2190658+hameerabbasi@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "pytorch-dev"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "./torch-build.sh"
update = "./torch-update.sh"
clone = "./torch-clone.sh"

[activation.env]
PYTORCH_BUILD_DIRECTORY = "${PIXI_PROJECT_ROOT}/git"
PYTORCH_PIXI_BUILD = "1"

[dependencies]
python = "3.9.*"
pip = "*"
cpython = "*"
gcc = "13.*"
gxx = "13.*"
gdb = "*"
clang = "*"
clangxx = "*"
lldb = "*"
magma = "*"
cuda-driver-dev = "*"
cuda-version = "12.6.*"
cudnn = "*"
conda-gcc-specs = "*"
cuda-libraries-dev = "*"
cuda-nvcc = "*"
cuda-gdb = "*"
cuda-nvtx-dev = "*"
cuda-nvml-dev = "*"
cuda-cupti-dev = "*"
ccache = "*"
cmake = "*"
fsspec = "*"
mkl = "*"
mkl-include = "*"
ninja = "*"
packaging = "*"
pyyaml = "*"
scikit-build = "*"
setuptools = "*"
sysroot_linux-64 = ">=2.17"
types-dataclasses = "*"
typing = "*"
typing-extensions = "*"
wheel = "*"
numpy = "*"
expecttest = "*"
hypothesis = "*"
lintrunner = "*"
scipy = "*"
psutil = "*"
pytest = "*"
ghstack = "*"
ipython = "*"
pytest-sugar = "*"
pytest-xdist = "*"
filelock = "*"
sympy = "*"
astunparse = "*"
dill = "*"
jinja2 = "*"
lark = "*"
optree = "*"
tabulate = "*"
networkx = "*"
zlib = "*"
halide-python = "*"

[pypi-dependencies]
z3-solver = "*"
